# -*- coding: utf-8 -*-
"""NN_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-01xVnlfGDf6MAVHgKVShc4uX09TKc3B
"""

# CSCI-5612 Neural Network Analysis - Ethan Piacenti

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# 1. Loading the training and testing datasets

from google.colab import files
uploaded = files.upload()   # Upload train_set.csv and test_set.csv from files
train_path = "train_set.csv"
test_path = "test_set.csv"
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

from sklearn.preprocessing import LabelEncoder

def encode_column(colname): # converts a categorical column into numerical values using LabelEncoder
    le = LabelEncoder()
    combined = pd.concat([train_df[colname].astype(str),
                          test_df[colname].astype(str)])
    le.fit(combined) #replaces the original categorical values with their encoded integers
    train_df[colname] = le.transform(train_df[colname].astype(str))
    test_df[colname] = le.transform(test_df[colname].astype(str))

# Encoding all categorical columns used by the NN
encode_column("isopenaccess")
encode_column("venue")
encode_column("journal_name")
encode_column("s2fieldsofstudy")
encode_column("label")   # target for classification

# Splitting features and labels
X_train = train_df.drop(columns=["label"]).values # removing the label column to create the input features for training.
y_train = train_df["label"].values
X_test = test_df.drop(columns=["label"]).values
y_test = test_df["label"].values

# verifying data was loaded correctly
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

# 2. Defing the Neural Network architecture

# Input dimension = number of features
input_dim = X_train.shape[1] # specifies how many neurons are needed in the input layer
model = Sequential()
model.add(Dense(8, activation="relu", input_shape=(input_dim,))) # hidden layer
model.add(Dense(1, activation="sigmoid")) # output layer

# Compile model with Adam optimizer and binary crossentropy loss
learning_rate = 0.001 # controls how much the network's weights are updated
optimizer = Adam(learning_rate=learning_rate)

model.compile(
    optimizer=optimizer, # Adam algorithm for updating weights
    loss="binary_crossentropy",
    metrics=["accuracy"] # tracks the classification accuracy during training and evaluation
)

# 3. Training the Neural Network (NN) model

epochs = 30 # how many times the training set will be passed over the NN
batch_size = 32 # specifies the number of training samples processed before the model updates its weights

history = model.fit(
    X_train,
    y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(X_test, y_test),
    verbose=1
)

# 4. Evaluating the testing dataset

# Predicting probabilities --> convert to binary labels (0/1)
y_prob = model.predict(X_test)
y_pred = (y_prob > 0.5).astype(int).ravel() # converting the predicted probabilities into binary class labels
test_accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {test_accuracy:.4f}")

# 5. Plotting confusion matrix, accuracy, and last five Epochs

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)

# Confusion matrix
plt.figure(figsize=(5, 5))
disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix - Neural Network")
plt.tight_layout()
plt.show()   # <-- DISPLAY INSTEAD OF SAVE/CLOSE

# Accuracy of last 5 epochs
train_acc = history.history["accuracy"]
val_acc = history.history["val_accuracy"]
train_loss = history.history["loss"]
val_loss = history.history["val_loss"]
last_5 = range(max(0, epochs - 5), epochs)
plt.figure(figsize=(8, 4))

# Plotting accuracy for last 5 epochs
plt.subplot(1, 2, 1)
plt.plot(last_5, [train_acc[i] for i in last_5], marker="o", label="Train Acc")
plt.plot(last_5, [val_acc[i] for i in last_5], marker="o", label="Val Acc")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Last 5 Epochs - Accuracy")
plt.legend()

# Plotting the loss for last 5 epochs
plt.subplot(1, 2, 2)
plt.plot(last_5, [train_loss[i] for i in last_5], marker="o", label="Train Loss")
plt.plot(last_5, [val_loss[i] for i in last_5], marker="o", label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Last 5 Epochs - Loss")
plt.legend()

plt.tight_layout()
plt.show()

# 6. Summary and Output of NN

print("\nModel Summary:")
model.summary()

print("\nFinal Test Accuracy:", test_accuracy)
print("Confusion matrix and last 5 epochs plots saved as:")
print("  nn_confusion_matrix.png")
print("  nn_last5epochs.png")